import type { Product } from "@/context/CartContext";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "White Portrait Graphic Tee",
    price: 400.0,
    category: "Tops",
    image: "/blindManWhite.jpeg",
  },
  {
    id: "2",
    name: "Classic Black Cap",
    price: 150.0,
    category: "Caps",
    image: "/cap.jpeg",
  },
  {
    id: "15",
    name: "Classic Blue Cap",
    price: 150.0,
    category: "Caps",
    image: "/capBlue.png",
  },

  {
    id: "3",
    name: "Black Crop Tee",
    price: 250.0,
    category: "Tops",
    image: "/cropTop.jpeg",
  },
  {
    id: "6",
    name: "Neon Pup Graphic Tee",
    price: 350.0,
    category: "Tops",
    image: "/dogGreen.jpeg",
  },
  {
    id: "10",
    name: "Skeleton Claw Graphic Tee",
    price: 400.0,
    category: "Tops",
    image: "/skeleton.jpeg",
  },
  {
    id: "11",
    name: "Volt Pup Graphic Tee",
    price: 350.0,
    category: "Tops",
    image: "/dogGreenYellow.jpeg",
  },
  {
    id: "12",
    name: "Classic Street Tee",
    price: 400.0,
    category: "Tops",
    image: "/normal.jpeg",
  },
  {
    id: "13",
    name: "Green Backprint Tee",
    price: 350.0,
    category: "Tops",
    image: "/greenBack.jpeg",
  },
  {
    id: "18",
    name: "Angel Babies Tee (Front)",
    price: 400.0,
    category: "Tops",
    image: "/babiesFront.png",
  },
  {
    id: "19",
    name: "Angel Babies Tee (Back)",
    price: 400.0,
    category: "Tops",
    image: "/babiesBack.png",
  },
  {
    id: "20",
    name: "American Drip Tee (Front)",
    price: 400.0,
    category: "Tops",
    image: "/americanFront.png",
  },
  {
    id: "21",
    name: "American Drip Tee (Back)",
    price: 400.0,
    category: "Tops",
    image: "/americanBack.png",
  },
  {
    id: "4",
    name: "Midnight Mosaic Hoodie (Front)",
    price: 450.0,
    category: "Hoodies",
    image: "/hoodieBlackFront.png",
  },
  {
    id: "23",
    name: "Azure Drip Hoodie (Front)",
    price: 450.0,
    category: "Hoodies",
    image: "/hoodieBlueFront.png",
  },
  {
    id: "8",
    name: "Crimson Street Art Hoodie (Back)",
    price: 450.0,
    category: "Hoodies",
    image: "/hoodieRedBack.png",
  },
  {
    id: "9",
    name: "Drip Vision Hoodie",
    price: 450.0,
    category: "Hoodies",
    image: "/mainHoodie.jpeg",
  },
  {
    id: "16",
    name: "Drip Vision Hoodie (Front)",
    price: 450.0,
    category: "Hoodies",
    image: "/mainHoodieFront.png",
  },
  {
    id: "22",
    name: "Midnight Mosaic Hoodie (Back)",
    price: 450.0,
    category: "Hoodies",
    image: "/hoodieBlackBack.png",
  },
  {
    id: "17",
    name: "Crimson Street Art Hoodie (Front)",
    price: 450.0,
    category: "Hoodies",
    image: "/hoodieRedFront.png",
  },
  {
    id: "5",
    name: "Essential Black Tote",
    price: 200.0,
    category: "Bags",
    image: "/bag.jpeg",
  },
  {
    id: "7",
    name: "Azure Drip Hoodie (Back)",
    price: 450.0,
    category: "Hoodies",
    image: "/hoodieBlueBack.jpg",
  },
];
